"""
neurosim/reconstruction/ingestion.py

Brain data ingestion and neural morphology reconstruction pipeline.

Supports:
- SWC morphology files (standard neuron reconstruction format)
- NeuroML2 model exchange format
- SONATA network format (Allen / BBP standard)
- HDF5 connectomics datasets
- Allen Brain Atlas API integration
- H01 (Google/Harvard human cortex dataset) format
- Electron microscopy segmentation data

Pipeline stages:
1. Load raw data (SWC/HDF5/JSON)
2. Validate and clean morphology
3. Build compartment tree
4. Generate synaptic connectivity graph
5. Export to simulation-ready format
"""

from __future__ import annotations
import numpy as np
import json
import logging
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Iterator
from pathlib import Path
from enum import Enum, auto
import struct

logger = logging.getLogger("neurosim.reconstruction")


# ─────────────────────────────────────────────────────────────
#  SWC point types (standard)
# ─────────────────────────────────────────────────────────────
class SWCType(Enum):
    UNDEFINED   = 0
    SOMA        = 1
    AXON        = 2
    BASAL_DEND  = 3
    APICAL_DEND = 4
    FORK_POINT  = 5
    END_POINT   = 6
    CUSTOM      = 7


@dataclass
class SWCPoint:
    """Single reconstruction point in SWC format."""
    id:         int
    type:       SWCType
    x: float          # μm
    y: float          # μm
    z: float          # μm
    radius:     float  # μm
    parent_id:  int   # -1 for root


# ─────────────────────────────────────────────────────────────
#  SWC morphology reader
# ─────────────────────────────────────────────────────────────
class SWCReader:
    """
    Reads SWC morphology files.
    Handles: standard SWC, eSWC (extended), multi-soma files.
    """

    @staticmethod
    def read(path: str) -> List[SWCPoint]:
        points = []
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) < 7:
                    continue
                try:
                    pt = SWCPoint(
                        id        = int(parts[0]),
                        type      = SWCType(int(parts[1])),
                        x         = float(parts[2]),
                        y         = float(parts[3]),
                        z         = float(parts[4]),
                        radius    = float(parts[5]),
                        parent_id = int(parts[6]),
                    )
                    points.append(pt)
                except (ValueError, KeyError):
                    logger.warning(f"Skipping malformed SWC line: {line}")
        logger.info(f"Loaded {len(points)} SWC points from {path}")
        return points

    @staticmethod
    def write(path: str, points: List[SWCPoint]) -> None:
        with open(path, "w") as f:
            f.write("# Generated by NeuroSim\n")
            f.write("# id type x y z radius parent\n")
            for p in points:
                f.write(f"{p.id} {p.type.value} "
                        f"{p.x:.4f} {p.y:.4f} {p.z:.4f} "
                        f"{p.radius:.4f} {p.parent_id}\n")


# ─────────────────────────────────────────────────────────────
#  Morphology validation and cleaning
# ─────────────────────────────────────────────────────────────
@dataclass
class MorphologyIssue:
    issue_type:  str
    point_id:    int
    description: str


class MorphologyValidator:
    """
    Validates and repairs common morphology reconstruction artifacts:
    - Duplicate points
    - Zero-length segments
    - Disconnected trees
    - Invalid radii
    - Self-intersecting branches
    """

    def __init__(self, min_radius: float = 0.01,
                 max_radius: float = 100.0,
                 max_segment_length: float = 1000.0):
        self.min_radius  = min_radius
        self.max_radius  = max_radius
        self.max_seg_len = max_segment_length

    def validate(self, points: List[SWCPoint]) -> Tuple[List[SWCPoint],
                                                         List[MorphologyIssue]]:
        issues  = []
        cleaned = []
        seen_ids = set()

        pt_by_id = {p.id: p for p in points}

        for p in points:
            # Duplicate check
            if p.id in seen_ids:
                issues.append(MorphologyIssue("duplicate_id", p.id,
                                              f"Duplicate point ID {p.id}"))
                continue
            seen_ids.add(p.id)

            # Radius bounds
            if p.radius < self.min_radius:
                issues.append(MorphologyIssue("min_radius", p.id,
                                              f"Radius {p.radius:.4f} below min"))
                p = SWCPoint(p.id, p.type, p.x, p.y, p.z,
                             self.min_radius, p.parent_id)

            if p.radius > self.max_radius:
                issues.append(MorphologyIssue("max_radius", p.id,
                                              f"Radius {p.radius:.4f} above max"))
                p = SWCPoint(p.id, p.type, p.x, p.y, p.z,
                             self.max_radius, p.parent_id)

            # Segment length check
            if p.parent_id != -1 and p.parent_id in pt_by_id:
                par = pt_by_id[p.parent_id]
                dist = np.sqrt((p.x-par.x)**2 + (p.y-par.y)**2 +
                               (p.z-par.z)**2)
                if dist == 0.0:
                    issues.append(MorphologyIssue("zero_length", p.id,
                                                  "Zero-length segment"))
                elif dist > self.max_seg_len:
                    issues.append(MorphologyIssue("long_segment", p.id,
                                                  f"Segment length {dist:.1f}μm"))

            cleaned.append(p)

        logger.info(f"Validation: {len(issues)} issues found, "
                    f"{len(cleaned)} points retained")
        return cleaned, issues


# ─────────────────────────────────────────────────────────────
#  Morphology → Compartment tree builder
# ─────────────────────────────────────────────────────────────
class MorphologyToCompartments:
    """
    Convert SWC point cloud into simulation-ready compartment tree.

    Algorithm:
    1. Build directed tree from SWC parent links
    2. Merge collinear points below length threshold (reduce n_comps)
    3. Assign biophysical parameters per section type
    4. Return list of Compartment objects
    """

    def __init__(self, max_comp_length: float = 50.0,
                 channel_mapping: Optional[Dict] = None):
        self.max_comp_length = max_comp_length
        self.channel_mapping = channel_mapping or self._default_channels()

    @staticmethod
    def _default_channels() -> Dict:
        from neurosim.models.neuron import CompartmentType
        return {
            SWCType.SOMA:        ["na", "k", "leak", "ca_l"],
            SWCType.AXON:        ["na", "k", "leak"],
            SWCType.BASAL_DEND:  ["na", "k", "leak", "ka"],
            SWCType.APICAL_DEND: ["na", "k", "leak", "ka", "hcn", "ca_l"],
        }

    def build(self, points: List[SWCPoint],
              neuron_id: int = 0) -> object:
        """Convert SWC points to MultiCompartmentNeuron."""
        from neurosim.models.neuron import (
            MultiCompartmentNeuron, Compartment, CompartmentType
        )
        from neurosim.models.ion_channels import build_channel

        swc_type_map = {
            SWCType.SOMA:        CompartmentType.SOMA,
            SWCType.AXON:        CompartmentType.AXON_HILLOCK,
            SWCType.BASAL_DEND:  CompartmentType.BASAL_DEND,
            SWCType.APICAL_DEND: CompartmentType.APICAL_DEND,
        }

        neuron   = MultiCompartmentNeuron(neuron_id)
        pt_map   = {p.id: p for p in points}
        comp_id  = 0
        pt_to_comp = {}

        # Process each point
        for p in points:
            swc_t = p.type
            if swc_t not in swc_type_map:
                continue

            comp_type = swc_type_map[swc_t]

            # Determine segment length
            if p.parent_id != -1 and p.parent_id in pt_map:
                par = pt_map[p.parent_id]
                length = max(0.1, np.sqrt(
                    (p.x-par.x)**2 + (p.y-par.y)**2 + (p.z-par.z)**2
                ))
            else:
                length = p.radius * 2

            # Clamp long compartments
            n_split = max(1, int(np.ceil(length / self.max_comp_length)))
            for _ in range(n_split):
                seg_len = length / n_split
                comp = Compartment(
                    id       = comp_id,
                    type     = comp_type,
                    length   = seg_len,
                    diameter = p.radius * 2,
                    x=p.x, y=p.y, z=p.z,
                    parent_id = pt_to_comp.get(p.parent_id)
                )

                # Add appropriate ion channels
                for ch_name in self.channel_mapping.get(swc_t, ["na", "k", "leak"]):
                    try:
                        comp.add_channel(ch_name, build_channel(ch_name))
                    except Exception:
                        pass

                neuron.add_compartment(comp)
                if comp_id == 0:
                    pt_to_comp[p.id] = comp_id
                comp_id += 1

            pt_to_comp[p.id] = comp_id - 1

        neuron.initialize(V_init=-65.0)
        logger.info(f"Built neuron {neuron_id} with {comp_id} compartments")
        return neuron


# ─────────────────────────────────────────────────────────────
#  SONATA network format reader (Allen / BBP standard)
# ─────────────────────────────────────────────────────────────
class SONATAReader:
    """
    Read SONATA-format neural circuit files (HDF5 + JSON config).
    Reference: Dai et al. 2020, https://github.com/AllenInstitute/sonata
    """

    def __init__(self, config_path: str):
        self.config_path = Path(config_path)
        self.base_dir    = self.config_path.parent
        self._config     = None

    def load_config(self) -> dict:
        with open(self.config_path) as f:
            self._config = json.load(f)
        return self._config

    def iter_nodes(self) -> Iterator[dict]:
        """Iterate over node (neuron) records."""
        try:
            import h5py
        except ImportError:
            raise ImportError("h5py required for SONATA format")

        cfg = self._config or self.load_config()
        for node_pop in cfg.get("networks", {}).get("nodes", []):
            h5_path = self.base_dir / node_pop["nodes_file"]
            with h5py.File(h5_path, "r") as f:
                pop_names = list(f["nodes"].keys())
                for pop in pop_names:
                    grp   = f[f"nodes/{pop}"]
                    n_ids = grp["node_id"][:]
                    types = grp.get("node_type_id", np.zeros(len(n_ids)))[:]
                    for i, nid in enumerate(n_ids):
                        yield {"id": int(nid), "type": int(types[i]),
                               "population": pop}

    def iter_edges(self) -> Iterator[dict]:
        """Iterate over edge (synapse) records."""
        try:
            import h5py
        except ImportError:
            raise ImportError("h5py required for SONATA format")

        cfg = self._config or self.load_config()
        for edge_pop in cfg.get("networks", {}).get("edges", []):
            h5_path = self.base_dir / edge_pop["edges_file"]
            with h5py.File(h5_path, "r") as f:
                pop_names = list(f["edges"].keys())
                for pop in pop_names:
                    grp  = f[f"edges/{pop}"]
                    srcs = grp["source_node_id"][:]
                    tgts = grp["target_node_id"][:]
                    wts  = grp.get("syn_weight", np.ones(len(srcs)))[:]
                    dly  = grp.get("delay", np.full(len(srcs), 1.0))[:]
                    for i in range(len(srcs)):
                        yield {"src": int(srcs[i]), "tgt": int(tgts[i]),
                               "weight": float(wts[i]), "delay": float(dly[i])}


# ─────────────────────────────────────────────────────────────
#  Connectomics data ingestor (EM segmentation)
# ─────────────────────────────────────────────────────────────
class ConnectomicsIngestor:
    """
    Ingest electron microscopy connectomics datasets.
    Supports: JSON skeleton files, HDF5 volume + skeleton data.

    Input formats:
    - CATMAID JSON skeleton export
    - CAVE/FlyWire/H01 connectivity tables (CSV/parquet)
    - WebKnossos NML format
    """

    def __init__(self, source: str = "catmaid"):
        self.source = source

    def load_catmaid_json(self, path: str) -> Tuple[List[SWCPoint],
                                                     List[Dict]]:
        """Load CATMAID skeleton export (JSON)."""
        with open(path) as f:
            data = json.load(f)

        points = []
        for node in data.get("treenodes", []):
            pt = SWCPoint(
                id        = node["id"],
                type      = SWCType.UNDEFINED,
                x         = node["x"] / 1000.0,  # nm → μm
                y         = node["y"] / 1000.0,
                z         = node["z"] / 1000.0,
                radius    = (node.get("radius", 100) or 100) / 1000.0,
                parent_id = node.get("parent_id") or -1
            )
            points.append(pt)

        connectors = data.get("connectors", [])
        return points, connectors

    def load_csv_connectivity(self, path: str) -> List[Dict]:
        """Load CSV connectivity table (src, tgt, weight, delay, syn_type)."""
        import csv
        connections = []
        with open(path, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                connections.append({
                    "src":      int(row["src_neuron_id"]),
                    "tgt":      int(row["tgt_neuron_id"]),
                    "weight":   float(row.get("weight", 1.0)),
                    "delay":    float(row.get("delay", 1.0)),
                    "syn_type": row.get("syn_type", "ampa"),
                })
        return connections


# ─────────────────────────────────────────────────────────────
#  High-level reconstruction pipeline
# ─────────────────────────────────────────────────────────────
class ReconstructionPipeline:
    """
    End-to-end pipeline: raw data → simulation-ready network.

    Stage 1: Load morphologies (SWC / SONATA / EM)
    Stage 2: Validate and clean
    Stage 3: Build compartment models
    Stage 4: Build connectivity graph
    Stage 5: Export to engine format
    """

    def __init__(self, output_dir: str = "reconstructed"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.validator   = MorphologyValidator()
        self.builder     = MorphologyToCompartments()
        self.neurons     = {}
        self.connections = []

    def add_swc_neuron(self, swc_path: str, neuron_id: int = None) -> int:
        """Load, validate, and build a neuron from SWC file."""
        points    = SWCReader.read(swc_path)
        cleaned, issues = self.validator.validate(points)

        if issues:
            logger.warning(f"  {len(issues)} morphology issues in {swc_path}")

        nid    = neuron_id if neuron_id is not None else len(self.neurons)
        neuron = self.builder.build(cleaned, neuron_id=nid)
        self.neurons[nid] = neuron
        return nid

    def add_connection(self, src: int, tgt: int, weight: float,
                       delay: float, syn_type: str = "ampa",
                       tgt_comp: int = 0) -> None:
        from neurosim.models.neuron import make_synapse
        from neurosim.simulation.engine import Connection

        if tgt not in self.neurons:
            logger.warning(f"Target neuron {tgt} not found")
            return

        tgt_neuron = self.neurons[tgt]
        syn = make_synapse(syn_type, weight=weight)
        syn_idx = len(tgt_neuron.synapses.get(tgt_comp, []))
        tgt_neuron.add_synapse(tgt_comp, syn)

        conn = Connection(
            src_id   = src,
            tgt_id   = tgt,
            tgt_comp = tgt_comp,
            syn_index = syn_idx,
            weight   = weight,
            delay    = delay,
        )
        self.connections.append(conn)

    def build_random_network(self, n_exc: int = 100, n_inh: int = 25,
                             p_ee: float = 0.1, p_ei: float = 0.5,
                             p_ie: float = 0.5, p_ii: float = 0.1,
                             rng_seed: int = 42) -> None:
        """
        Generate a random excitatory-inhibitory network
        using pre-built canonical cell types.
        """
        from neurosim.models.neuron import (
            build_l5_pyramidal_cell, build_parvalbumin_interneuron
        )
        rng = np.random.default_rng(rng_seed)

        # Excitatory neurons
        for i in range(n_exc):
            self.neurons[i] = build_l5_pyramidal_cell(neuron_id=i)

        # Inhibitory neurons
        for i in range(n_exc, n_exc + n_inh):
            self.neurons[i] = build_parvalbumin_interneuron(neuron_id=i)

        exc_ids = list(range(n_exc))
        inh_ids = list(range(n_exc, n_exc + n_inh))

        # Random connectivity
        def connect(srcs, tgts, p, syn_type, w_mean, w_std, d_mean):
            for s in srcs:
                for t in tgts:
                    if s == t:
                        continue
                    if rng.random() < p:
                        w = max(0.01, rng.normal(w_mean, w_std))
                        d = max(0.1, rng.exponential(d_mean))
                        self.add_connection(s, t, w, d, syn_type)

        connect(exc_ids, exc_ids, p_ee, "ampa",   0.5, 0.1, 1.5)
        connect(exc_ids, inh_ids, p_ei, "ampa",   0.8, 0.15, 1.0)
        connect(inh_ids, exc_ids, p_ie, "gaba_a", 1.2, 0.2, 1.0)
        connect(inh_ids, inh_ids, p_ii, "gaba_a", 0.6, 0.1, 0.8)

        logger.info(f"Built random network: {n_exc} exc + {n_inh} inh neurons, "
                    f"{len(self.connections)} connections")

    def export_to_engine(self, engine) -> None:
        """Populate a NeuralSimulationEngine with this network."""
        for nid, neuron in self.neurons.items():
            engine.add_neuron(neuron)
        for conn in self.connections:
            engine.add_connection(conn)
        logger.info(f"Exported {len(self.neurons)} neurons, "
                    f"{len(self.connections)} connections to engine")
